[samplerbox]
; LOG_LEVEL = DEBUG
gain = 0.2

[fluidSynthSettingsFloat]

[fluidSynthSettingsInt]
audio.periods = 2
audio.period-size = 64

[fluidSynthSettingsString]
audio.driver = pulseaudio

[channel0]
BANK = 0
PROGRAM = 3

[channel9]
Bank = 1
Program = 5