[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "samplerbox"
version = "0.0.1"
dependencies = [
    "pyserial", "python-rtMidi", "pyfluidsynth"
]

[tool.setuptools]
py-modules = []