[build-system]
requires = ["setuptools", "cython", "numpy"]
build-backend = "setuptools.build_meta"

[project]
name = "samplerbox"
version = "0.0.1"
dependencies = [
    "sounddevice", "pyserial", "numpy", "python-rtMidi", "pyfluidsynth"
]

[tool.setuptools]
py-modules = []